### ISSUE TITLE
lead 8 bass lead underline error

### ISSUE THREAD

**Issue by phydokz** [gleitz/midi-js-soundfonts#11]
in [lead_8_bass__lead-ogg.js](https://github.com/gleitz/midi-js-soundfonts/blob/master/FluidR3_GM/lead_8_bass__lead-ogg.js) and [lead_8_bass__lead-mp3.js](https://github.com/gleitz/midi-js-soundfonts/blob/master/FluidR3_GM/lead_8_bass__lead-mp3.js)
MIDI.Soundfont.lead_8_bass_lead should be MIDI.Soundfont.lead_8_bass__lead

**Comment by gleitz** [comment]
Would be happy to accept a pull request!

**Comment by gleitz** [comment]
Finally found the issue: https://github.com/gleitz/MIDI.js/commit/3f4fefe311899c3712156675ec04467db8137876
