### ISSUE TITLE
Links in README.md do not work

### ISSUE THREAD

**Issue by ghost** [gleitz/midi-js-soundfonts#13]
Hi, and first thanks for these sounds. Maybe you could merge master branch in gh-pages, and choose gh-pages as the default branch, maybe then remove master.

**Comment by gleitz** [comment]
Good idea. Looks like I need to follow [these steps](http://www.xanthir.com/b4Zz0).

**Comment by gleitz** [comment]
Done.

**Comment by ghost** [comment]
Ok Now gh-pages is the default however it seems that you haven't merged
master in gh-pages before providing gh-pages as default. So the json files,
and links in readme have gone. Do you still have the master branch on your
local machine in order to merge and push?

**Comment by gleitz** [comment]
Ah good point. Merged in https://github.com/gleitz/midi-js-soundfonts/pull/14

**Comment by ghost** [comment]
Now it's OK thanks.
