### ISSUE TITLE
Only grand piano soundfont works

### ISSUE THREAD

**Issue by MeLight** [gleitz/midi-js-soundfonts#17]
Downloaded the library, tried to play with some sound fonts. Only default `acoustic_grand_piano` works. Tried downloading installing `guitar_acoustic_nylon` from provided fonts, it loads but doesn't make any sounds. Same for default `synth_drum` - loads, but no sounds.

**Comment by gleitz** [comment]
Generally this means you're not configuring the instrument properly. Would you link to an example that fails?

**Comment by gleitz** [comment]
http://blog.gleitzman.com/post/63283830260/midijs-playing-audio-in-the-browser-with

**Comment by MeLight** [comment]
Just noticed that i also need to provide instrument number. Thanks!

**Comment by ddugovic** [comment]
I too struggled with this when I started using the library & I suspect many users to come will also struggle similarly.
