### ISSUE TITLE
Add percussion samples from soundfonts

### ISSUE THREAD

**Issue by adarob** [gleitz/midi-js-soundfonts#18]
It looks like the percussion (channel 10) samples aren't in the repo. Is it possible to add them?

**Comment by supersational** [comment]
Needed this as well so I added them [in this repo](https://github.com/supersational/midi-js-soundfonts), enjoy!

P.S. some notes will be missing since they are not part of the [GM percussion spec](https://en.wikipedia.org/wiki/General_MIDI#Percussion).

**Comment by paulrosen** [comment]
@supersational , would you consider making your change a pull request? This is a great, standard place to get soundfonts. It would be nice to have Channel 10 supported here.

**Comment by supersational** [comment]
@paulrosen sure thing! [https://github.com/gleitz/midi-js-soundfonts/pull/25](https://github.com/gleitz/midi-js-soundfonts/pull/25)
