### ISSUE TITLE
[doc] readme: update link to soundfont-generator

### ISSUE THREAD

**Issue by mk-pmb** [gleitz/midi-js-soundfonts#22]
Hi there,
I'm looking for ways to convert a custom sf2, so I followed the "soundfont-generator" link in the readme but it's broken (404). <del>How can I convert it?</del>

Update: [Found it](https://github.com/gleitz/MIDI.js/tree/master/soundfont-generator). Now this issue is just about updating the readme.

**Comment by gleitz** [comment]
Would you submit a PR with the corrected links? Thx!

**Comment by mk-pmb** [comment]
Ok, I'm on it. Would you like a `package.json` for npm as well?
<del>Update: Oops, that git-clone will take a few hours. Maybe I can PR tomorrow.</del>
Update: Found [how to use git sparse checkout](https://gist.github.com/mk-pmb/fbc98efeb77fa991b32ef6552eb2b2ee). Update 2: Still very large. :-(

**Comment by gleitz** [comment]
Lol yeah it's a pretty big repo. A package.json is not a bad idea. No rush and thanks for the help.

**Comment by mk-pmb** [comment]
As for the `package.json`, there seems to be a license conflict between MIT in `LICENSE.txt` and the CC-BY-SA-3.0 of Musyng Kite, how should I resolve it?

**Comment by gleitz** [comment]
Which of the two licenses (Creative Commons Attribution 3.0 license and Creative Commons Attribution Share-Alike 3.0 license) would both fall into? Let's go with that one.

**Comment by mk-pmb** [comment]
In my layman interpretation (I'm not a lawyer) of CC-BY-SA-3.0 and MIT, their works cannot be unified into a work with just one license. I'll make a package.json with bogus license field for now, then someone else can easily update it once the legal stuff is resolved.

**Comment by gleitz** [comment]
Cool thx.
