### ISSUE TITLE
Accessing files from the repo

### ISSUE THREAD

**Issue by rsveltman** [gleitz/midi-js-soundfonts#24]
Hi, the readme says we can fetch the files directly, but it's being wonky for me and I'm having trouble figuring out why (I'm new to JS).

I'm using mudcube/MIDI.js. Here's what I'm trying to do:
```
MIDI.loadPlugin({
		soundfontUrl: "http://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/",
		instrument: "marimba",
		onsuccess: function() {
			var delay = 0; // play one note every quarter second
			var note = 50; // the MIDI note
			var velocity = 127; // how hard the note hits
			// play the note
			MIDI.setVolume(0, 127);
			MIDI.noteOn(0, 21, velocity, delay);
			MIDI.noteOff(0, 21, delay + 0.75);
		}
	});
```
This is just following the example from mudcube, only instead of using the local directory "/example/soundfont/" I'm using the repo.

Problem: it only works if the value of `instrument `is "acoustic_grand_piano". Any other instrument will not play any sound. I'm using the Source Inspector to try and find out what the problem is, but it says it works even when I change the instrument. I'm not getting an error. But the sound won't play. I tried this with a few different instruments. Any idea why this happens?

**Comment by gleitz** [comment]
Check out https://github.com/mudcube/MIDI.js/blob/master/README.md for how `noteOn` works and channel/note selection works.
