### ISSUE TITLE
Convert samples

### ISSUE THREAD

**Issue by laven2** [gleitz/midi-js-soundfonts#26]
Hello, i have some samples for piano in wav, how to configure a covert in mp3/ogg - that would get the best sound? I tried to cbr and every note breaks off a second after the start, in the vbr the note breaks off later, but there is no effect of finishing(release) it like in the acoustic grand piano

**Comment by gleitz** [comment]
Are you asking how to convert wav files to mp3? There are probably a bunch of answers to that on StackOverflow. 
I have always gone from wavefonts to midi-js readable format so now exactly sure how to do that by hand

**Comment by nsmortis** [comment]
@gleitz I will try to rephrase the question. Is it possible to use any library of samples using this library? As for the format of mp3, everything is clear. For example - I load my piano samples library (not FluidR3_GM' or 'MusyngKite) with several layers of volume and without changing a line of code the result is erroneous. The notes are played back with the counters and the piano pedal function stops working

**Comment by gleitz** [comment]
That's not really supported by this repo. You could try swapping out the audio files within one of the existing libraries like `FluidR3_GM`, but if the length of the audio file changes then that might be encoded elsewhere so it could result in the audio being cut off.
