### ISSUE TITLE
Adblocker and chrome extensions lead to errors

### ISSUE THREAD

**Issue by MotifaiMusic** [gleitz/midi-js-soundfonts#28]
I get net::ERR_BLOCKED_BY_CLIENT errors from line 290 in soundfont-player.js. It goes away when I turn adblocker off. 

My solution was to download the soundfonts I use and update the URL in soundfont-player.js to point to my server. I'm curious if there is a way to avoid modifying the source. Maybe moving files to a CDN? The other CDNs I use had no issues. Happy to help if you have a preferred solution.

**Comment by gleitz** [comment]
If you can find a good solution then I'd accept a PR (or update to the README about the cdn)
