### ISSUE TITLE
Fat Boy names.json has extraneous instruments

### ISSUE THREAD

**Issue by RobAley** [gleitz/midi-js-soundfonts#33]
Hi,

The names.json file for Fat Boy lists synth_strings_1 & 2, but these sounds aren't present as .js or .mp3 samples. Is the names.json wrong or are the sound files missing (or am I missing something?)

Thanks

Rob

**Comment by gleitz** [comment]
You're right! I dug a bit deeper into why this happened. More info here https://github.com/gleitz/MIDI.js/commit/3f4fefe311899c3712156675ec04467db8137876 but essentially MIDI.js does not match the MIDI association spec, but my soundfont-generator does, so this caused compatibility issues.

I will be re-uploading all soundfonts with corrected filenames, fondernames, and `names.json` files.
