### ISSUE TITLE
Use soundsfonts without fetching?

### ISSUE THREAD

**Issue by jgarte** [gleitz/midi-js-soundfonts#39]
Hi,

How do you recommend I use the soundfonts without fetching them over the internet?

I'm having issues such as the following:

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://gleitz.github.io/midi-js-soundfonts/MusyngKite/acoustic_guitar_steel-ogg.js (“default-src”).
```

**Comment by gleitz** [comment]
`github.io` should support CORS. You might want to check and make sure the site you're creating has the correct Content Security Policy.

https://stackoverflow.com/a/37308542/305414

Alternatively, you could clone this repo and serve the soundfonts from the same origin as your website.

**Comment by jgarte** [comment]
Thanks for the reply. I ended up vendoring the js files that I needed in order to avoid this issue:

https://jgart.whereis.みんな/#/

**Comment by gleitz** [comment]
すばらしい

nice work!
