### ISSUE TITLE
Does the soundfont file contain drum sounds?

### ISSUE THREAD

**Issue by clubfest** [gleitz/midi-js-soundfonts#5]
I saw a chart about the sound for channel 10 being:

35   Acoustic Bass Drum  
 36   Bass Drum 1  
 37   Side Stick  
 38   Acoustic Snare 

Are those in the soundfont file you use?

**Comment by drumnation** [comment]
I realize this is a really old topic, but I was wondering if anyone knows how I would go about getting this to convert/generate the percussion sounds from the SoundFont or would anyone recommend a better way to have the drum channels from a midi file play "standard kit"?
