### ISSUE TITLE
Use github to serve files (via gh-pages)

### ISSUE THREAD

**Issue by danigb** [gleitz/midi-js-soundfonts#9]
Hi,

I'm the creator of [soundfont-player](https://github.com/danigb/soundfont-player), a small library that uses your prerender .js files to load soundfonts. 

Currently I'm using a proxy (rawgit.com) to deliver the files to the browser, but this is not suitable for production.

And that's my proposal:
- Create a gh-pages branch with the contents of master
- Set gh-pages as default branch
- Remove master branch

Then, we could access the files via gleitz.github.io/midi-js-soundfonts...

What do you think?

**Comment by cristiancd** [comment]
Perfecto!!



Cristian Cornejo Droguett
*+56965368574*

*"Innovar: La Clave del Crecimiento"*
 [image: skype] [image: facebook] <http://facebook.com/ccdroguett> [image:
twitter] <http://cristiancd/>   [image: YouTube] <http://./>

[image: eco] No me imprimas si no es necesario. Protejamos el medio ambiente

2016-05-19 9:34 GMT-04:00 danigb <notifications@github.com>:

**Comment by gleitz** [comment]
I would be happy to accept a pull request for the gh pages branch, but why exactly do we have to delete the master branch. That might be confusing for people who check out code and expect to see master.

**Comment by danigb** [comment]
Hi, 

I don't think I can do the pull request without permission to upstream (http://stackoverflow.com/questions/9796370/github-pull-request-to-a-new-upstream-branch).

But it should be really simple for you:

```
git co -b gh-pages
git push -u origin gh-pages
````

It's not necessary to delete master branch, but I think that approach has some advantages. Remember that only things in gh-pages branch are be published, so if you keep master as default branch, you need a second step to publish the changes (commit to the master, then merge changes to gh-pages). Having two branches, in my opinion, can create doubts to the users about where to apply the changes or where are the recent changes. With only one branch, there's no doubt of where the stuff is (and branch names are just that, names. There's no difference between master or gh-pages or whatever it is named). 

Anyway, I will do a little more research to know if I can make the PR.

Regards,
Dani

**Comment by gleitz** [comment]
Created the branch for you.

**Comment by danigb** [comment]
Hi,

Thanks! That's basically all. Now soundfont files are accessible through github.io: http://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/reed_organ-mp3.js

Now you have to decide if keep the master branch or not, and add a note to the README. I'll do a PR to the latests.

Thanks.
